# Generated by Django 4.0.6 on 2022-08-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_notification', '0002_notification_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
